const chatSearchableFields = ['userName'];
const excludeFields = [
  'sortBy',
  'sortOrder',
  'sort',
  'search',
  'limit',
  'page',
  'fields',
];

export const chatSearchFields = {
  chatSearchableFields,
  excludeFields,
};

export const ChatMessages = [
  'understandable man! We gotta know when to not push it anymore.   Hope some big Ws waiting when u start back up',
  'thanks very much for.. great luck to you',
  'hope your session going well buddy❤️',
  'hello, everyone! have a gret day ! 🍀🍀🍀',
  'how do i sound dumb ur just rain/tip farming smh',
  '💞',
  'busted',
  'bro its funny how rigged i t is these days',
  'Deposit Pending\n4 days ago\nYour deposit of \n$14.59\n has been registered and awaiting confirmation Did u do that depo for me?',
  'i feel scammed',
  'Busted',
  'glhf',
  'a "paying of my shit" hit is such a relief man',
  'Rb slacking again',
  'not me bro😑',
  'You aswell! 😊',
  'were same busted too',
  'I wonder what my top will be with 7 million wagered and 300k loss lol',
  'Good morning blackjack funrs',
  'Greetings dear mod, have a nice shift ahead  👉🌹🌹🌹',
  'Hello',
  'Some yall targets testing my patience',
  'Deposit Pending\n3 days ago\nYour deposit of \n$9.08\n has been registered and awaiting confirmation. Or this one?',
  'now they will turn your RTP again broo',
  '4 days ago smh',
  'good to hear man lil🧃?',
  'hits different for sure, felt so fucking good,',
  '🍀🍀🍀',
  'Joe burnt',
  'good luck always bro❤️✨🍀',
  'like 10-15k',
  'wager',
  'Hehe yea i hope it gives some good Karma! :D i mean its unicorn coins!',
  '“Taggers” let the man breathe ffs',
  'Hey beautiful ',
  'enjoy and dont give it back 🤜🤛',
  'lol 9$ depo',
  'show me the ppl u milked for tips, nice 9 to 5',
  'if i can run this back up i got you for sure, not a problem my guy',
  'hey hey , spacey',
  'Lol',
  'damn and im mad about my 6k loss this month',
  'Best of luck to you aswell! 😊🤞🏼🍀',
  'yess for sure gl bro u deserved it',
  'gl man',
  'it was what i had u dumb fuck',
  'may ur day b easy .. 🍻 thnk you',
  '',
  ' ',
  'Hello everyone, have a great day! ',
  "that's been my game plan since the other week, im really getting ahead by withdrawing and not chasing",
  '41 cents and wallet 91% To help try to move my  Iguess or am I just screwed till I get paid like any good low game wager',
  "no luck here but I'm rooting for you 🍀✨❤️ enjoy",
  'How are you today? :)',
  'Yeah I’m fucking sick about it but what can you do…I’ve been just collecting reloads rebuilding. I’ll recoup about 50-60k when it’s said and done.',
  'Hello there',
  'hello hello , hows your day!',
  'what happen man',
  'Cart right.  4',
  '💞',
  'hello ',
  'milked me for a while but it’s all good. I like to be used and abused.',
  'Gm',
  'u sound so judgemental lile i dont send tips',
  'take it easy dont get angry lol',
  'run it up',
  'hi beggars',
  '🍻',
  'Good evening, sweet Aleksa  💛 Have a lovely shift.',
  'Hi',
  'nothing',
  'popcorn it is',
  'There, baby is bathed, depo is in, play some bonzai while i wait for my breakfast and tims to get here. Life is good. Good luck folks.',
  'my luck sleeping',
  "Oh beer, don't mind if i do  ",
  'well, your bonuses should bring you back a bit but think about playing again pretty hard. Do you really need it?',
  'Hard minus today 🗿🔥',
  'life is not good',
  'Watch what u say next cause I probably will tip u again. Just wear those stripes proud lil bro',
  'u on it now bro?',
  'cmon blackjack fun. some greens',
  'soudns quality, good luck ! what a morning haha',
  'u became a hater and that i will never forget man i sent u tips nd u never sent back so many times but u remember mine like everyday',
  'bro just bet $1k on a 300x nba player prop today and boom easy 300k',
  'Hello Everyone 💚 Best Of Luck Today 🍀',
  'i dont care if you send tips or not your 24/7 here being fake, passive begging, go beg on the streets',
  'bad actually didnt sleep sun is beaming i cant even go outside to depo lolol .. hows ur day so far ?',
  'not again. zero again',
  'Oh boy. Not wise words sir. Gg',
  '🙄',
  'Good afternoon <3',
  'man i love yall lmao',
  'what game you play on? ',
  'how many you hit in last 3 months? I want in on it if its easy',
  'O grats my shqipe <3',
  'Hello, good afternoon. ',
  'Let me bring some pop corns',
  'who is real you? Dont get me started man fk off',
  '',
  'love',
  'Good',
  'ugh',
  'Good morning  ita a great day.. embrace it.. good luck today. Sending positive vibes your way.',
  'well, some of you',
  'hey, have a nice shift ahead',
  'wc back and enjoy G',
  'what was the prop bet',
  'Not at all my friend thats the way it should be allqYs share alcohol and drugs with friends 😂😂😂😆🍻',
  'started with what exactly go for it',
  'Damn bro, 7 million wagered and a 300k loss sounds like straight-up boss level pain, but mad respect for still standing and grinding through it.',
  'likewise!',
  'Have a nice day at work Cute Mod  ',
  'Hello there Spacey, how is it going today  ',
  'im already done with it, nothing hit lol im chillin right now',
  'good afternoon brothers      ',
  '<3 a ka naj tip bruda <3',
  'i owe him apparently.  Sir please do not yell at me. I’m sorry I wasn’t able to keep up with your sens.You are too big of a baller for my ass',
  'Goddd',
  'congrats 🔥',
  'Not at all my friend thats the way it should be allqYs share alcohol and drugs with friends 😂😂😂😆🍻',
  'oh shit my bad bro',
  'nubase needs to learn me how to hit 1mx within 1000 bets forreal',
  'if i had the the balance to do it ide hit many cant drop 1k when i rip building in casino 300x player prop is easy',
  'cmon fbot',
  'Howdy boys, hope you have a great day!  🤍',
  'hey hey   💚',
  'yeee get em brother,',
  'a slow day, my dear space!',
  'Like i said Fuck off',
  'scam ass rigged ass site hope owner d',
  "It's okay, how abouf you?  I just had a beer  ",
  'anyone else having a problem with depoing usdc',
  'he needs to learn it to  also, my man grinding for months',
  'Calm and good  Hope you are doing good as well ',
  'Well good luck today everyone hope blackjack fun is good to you',
  'watch ill go make one right now that will win today',
  'Bruh Allen really',
  'Whale a g',
  'dude is literally 24/7 here trying to milk ppl, so shameless',
  'everyone is olike that',
  "Have a good shift. I hope you're doing well.",
  'No more tip?!?!??',
  'there is a few of them out here lol gotta keep your circle tight for sure.',
  'I wish i could have had one too  Oh well  Not too bad, busy day today, a bit exhausted ',
  'my usdc i sent here says completed but never hit my account and its the same exact usdc addy',
  '    ',
  "How's flower and how's your health? :)",
  '',
  "That's what i like to hear, thanks bud ",
  '',
  '',
  'What the actual FUDGE did i just miss!? omfg',
  'comeon hornybot get me get',
  'go concentrate on ur game nd stop talking trash that will help u more',
  'has top monthly come out?',
  '',
  'congrats',
  'yeh',
  'what do you mean bro?',
  'sad',
  "You like beers?  Why are you exhausted? Didn't sleep enough? :)",
  'its 16 dollars relax',
  'ive had my fair share of interactions with him. It’s fine if you want to be a “user” but don’t deny it. But false promises are for the birds',
  'yikes',
  'Boooom',
  'Good morning',
  'holy that wouldve been insane',
  'i ment to say get me wet',
  'Can someone pull down the rollers on the sun plz ??!! 🫣👽',
  'keep on ',
  "we are all fine, she will be 10 on wednesady! and I'm fine,thank you for always asking",
  'Ask support usually usdc is fast',
  'u see u were right small bet always does it gl bro 😂',
  'omfg',
  'How are you guys doing?',
  'thank you   so far so good :)  How are you ?',
  'my usdc never hit my account but said completed and support wont get back to me',
  'bad, lost all',
  'Creative',
  'yooo',
  "let's goo G",
  'Gonna grab a bottle od scotch and go cry in a corner for abit',
  'he exactly what i said he is  sends u a dollar now u owe him for life lmao',
  'Awakening mom',
  'still luck not found here',
  ' wheres dad',
  "ty it's like u knew.lmao",
  'no luck here',
  'Running with devil.',
  'clown site',
  'dreaming of it i wish i could',
  'Have a blessed day y all',
  'yes best decision bro 😁 scotch 🥃',
  'what up homies juice the young kid',
  'send them to me on tg when you do. If i get a banger gonna share with you. 300x is banger parlay',
  'Hehehe, 10 :) it must be bittersweet seeing her get older. Say spacey said hi  💕',
  'Wake and bake then plinko time.',
  'thats what im saying it never even showed pending but its the same addy',
  'True..truee...! 💞',
  'Wake up again',
  'hi',
  '',
  '',
  'hiii',
  'hello G',
  'hay',
  'i have never told anyone here they owe why u trying to drive a dead narrative what dyu gain from that?',
  'if I went back and added it all up I probably sent 90% more and it’s all good but don’t lie in chat saying all this nonsense.',
  'Anyone knows free app that i can earn crypto?',
  'Lolhwhe',
  'rtp 0% luck 0% predetermined 100%',
  "I'm fine as well. Thank you for asking.Glad to know you're doing good. How are things at home?",
  'freecashapp',
  'Crazy potential',
  'Good morning sir',
  'Ima win',
  'I fell into the trap',
  'Support will get back to you eventually, just have patience, there might be high traffic',
  '😝',
  'You actually get free from. That cash app',
  "good luck bro i hope you're doing well 😊 😘",
  'It’s only Tuesday, fok',
  'no let him lie u encouraged him dont stop now 😂',
  'like who tf cares at the end of the day. I can’t get those funds back but be grateful. Not a little prick',
  '  ',
  'Freecsh surveys sucks',
  ':/',
  'yes you can depo straight into blackjack fun lmao',
  'VIP Achievement',
  'lol',
  'Keeping the lines open',
  'put me in coach',
  'Lol l',
  'Lol',
  'always red today dam',
  'Ugh',
  '🫶🫶',
  'exactly lmao',
  'thank you! hey, she is suprisingly lively!',
  'super cool  had some construction that finished 3 days ago, waiting for Friday to rest finally :) Short leave coming soon so u know, Life is good',
  'its hard to win today',
  'wow im done for today can hear any more shit ahhaaha',
  'Fuck me brooo!!!',
  'rise and shine hawk',
  'wen plat 6',
  'Love to see some RTP back blackjack fun, kinda missing a lot on my account!',
  'yeah its hard mate',
  'did that dog myst paid u man?',
  'Sorry to hear that   :(',
  'Ffs',
  'not funny anymore dude. U hurt my feelings saying I owe u a  sen.   Should’ve bit your tongue. Thought u were smarter.',
  'another depo today',
  'she is a HOE, she gives head in the capital broski',
  'busted',
  "That's great to know.  What plans do you have for her birthday?",
  'good luck on that buddy',
  "Yes it's been an unluck day for sure my luck has dropped",
  'That’s a rip',
  "soon broda don't worry",
  'what a rough day',
  'noooo really?',
  'as usual, picnic at my forest cottage, barbeque, nature',
  'i never told u i owed u even once i only said i sent u last that does not mean the same thing man',
  'yeah its rough day',
  'wow u got skemmed',
  "That's great. What kinda construction was this? :D",
  '      ',
  'Very tough 😔',
  "I don't like beers too much, they are just okay, I'm more of a whiskey or bourbon kind of guy, vodka is okay too",
  'Sir save your chats. We good.',
  'If you look at all the affiliate leaderboard compared to last month, there is been an decrease in wager by like 500% lmao, its actually sad.',
  'hope can hit some good today',
  'not only u',
  'wish you luck budd',
  'Rb been slacking today',
  ' I deserve second chance, so wen eddie wen?',
  "Check my history  from 3 hours ago and you'll find the same answer from me.",
  'W skem',
  'I think you will get top monthly this month with 200k wager is actually sad',
  'Learned it the hardway that yappers saying that the will send on their win just worth nothing',
  'always no win dam',
  'Unicorns everywhere 😂😂🍀',
  'Let it be know if u had any doubts   U dont owe me i never tipped anyone and requested a tip back based on that before',
  'I need a second chance. Completely broke now fuck',
  'wasted 50$ like nothing lol',
  'And they scooped the whole ATM machine now i gotta drice to center to depo omg i just remembered this fuuuuuuuuck.. no hope im done for now i guess',
  'How are doing?',
  'yeah $30',
  'here we go again lose',
  'Hi',
  'Do i realy need to scroll for 3 hours of your chat log ',
  "Wow, that's great. Forest cottage? Huh? When are you inviting Turtle and space?   🐢🌌❤️",
  'lmao',
  'blackjack fun is like a washing Machine..Always on rinse cycle🤑🤑🤣🤣🤣💩💚🟢💩🍀💚',
  'Doing great, how about you sir?  ',
  'hi buddy',
  'people are leaving blackjack fun or jusst run out of money?',
  'hey, i guess you missed all the talk about it. you are already invited. nemanjapi is in charge of the cetering',
  'Hi',
  "No, I'm just telling you how someone asked me something about beers and i said the same xD It was a figure of speech.  finally something co",
  'hows your game guys ?',
  "Happy thoughts here positive attitudes doesn't matter the size of tip or rain it's nice to get one",
  'lots of stuff and a lot of mess, creates mess in my head straightaway, so I have a lot of cleaning left to do... /// yikes   :)',
  'hello dear',
  'nice attitude! i wish you all the best! 🍀🍀🍀',
  'Let’s go limbo!!',
  'I really dont know, but I was look at leaderboards, and they are all 500% lower that months before lmao',
  "Wow, you guys made plans and I wasn't there ",
  'busted',
  'Lost it allll hahahaha',
  'if u been skemmed and have tg shots we can do a nice topic on forum',
  'Awe. Lol',
  'Ggg',
  'GG knows bro 😁 gl gl finger crossed for your max win 🤞🤞',
  'not good bro',
  'Oh, okay okay  great minds think alike ',
  'probably a mix of blackjack fun really bad RTP, players broker, players quitting',
  'is the slots hot today?',
  'Bike great full for what people gave me gave me a chance for a spin or 2',
  'nothing',
  'more like group plans. i need some help installing some solar panels. i think zhestka is coming, too',
  '',
  "Oh, i feel you. Mess around, means mess in my head.  Hugs hugs. You'll get through. We're sensitive souls.",
  'Rinsed every day, u know what that means!',
  'Guys who needs Scamming?',
  'yeah still reds',
  'I dont go about dragging people for 10$ i sent them 3months ago its written in the chat rules A tip is not a Loan. Its u guys doin the crying',
  'yes i can feel that pain bro',
  'i recieved it earlier already, so hopefully someone else wants it',
  'Nooo missed out on a 400.. well might come again x)',
  'is the slots hot today?',
  'Ppl keeping tabs on tips',
  'wish you all the best',
  "Do you have a favorite whiskey? //  Of course, he's coming. He's my +100, sorry i have like 100 best friends xD",
  ' ',
  'yeah bro keep tryy',
  'who are you talking about btw?',
  'Funny fucks everywhere bro',
  'they should be muted for a week if they are crying for their tip back',
  'sad',
  'ARE THE SLOTS HOT TODAY?P?',
  'when I come back from holiday I have more things to do   so deep depression until next year I guess 😅',
  'nope',
  'Fucking hilarious',
  'no',
  'I m noob',
  'wats up',
  'le bandit',
  'as crazy as it gets I ges',
  'see its that easy lock 320x player prop ',
  'i mean that would be great cos this guy in particular be on it everyday',
  'avoid using caps please',
  'Any good wins guys?',
  'theyre burnin and i aint got capital fuck',
  'Stay positive today. It’s the way',
  'Ive told you guys always how aparise is, but you guys never listen lmao, dont tip him, you will get nothing or just 25% back',
  'I keep on fighting mate! these unicorn coins gotta have a goldpot at the end of the rainbow ,D',
  'why you only do overs?',
  'i have withdrawn 16700 inr yesterday its \nshowing withdrawal successful but still i  have not recieved to my account can anyone please  clarify  my doubt',
  'Check with support please',
  '    thanks rain <3',
  'Can u see that ?   did i ask u to type that? Am sure you speaking from experience',
  'Sir if my bitching moaning and complaining constantly each and every day bothers you there always the ignore feature.',
  'no big wins',
  'oh yah finger crossed for ur flame bro',
  'Shit',
  " It's gonna be ok, dear. Clear your head at the same time. Balance is the key. The mess will always be there, also gotta learn to accept it.",
  '',
  'gl brother hit a max win soon ',
  '😊🤞🏼🍀🔥',
  'oh no, someone tipped me 56 cents three months ago, so I owe them with compounded interest total $6,782.72 lol',
  'cause im propping their all stars crazy to under their star players',
  'Yes, that was needed',
  'bro I am saying this for months but nobody listens hahaha, he scammed  hard,he asked for a loan and paid 30% back and said it was cool',
  "i hope I'll get sime whiskey after that 5k flame  ",
  'Nice',
  'I hope so',
  'cheers!',
  'Keep grinding yo',
  'Ohyea 2 bottles minimum ,)',
  'At the rate they are going u have to add an arm and a Leg 🦵 😂😂',
  'uhmm 20 cent rain dayum ',
  '😎',
  'okey, gonna put a lil bit of something on it to test you out 😎',
  'wen p2',
  'should i put my house on a 81x keno',
  'yes',
  'yea I been saying I’m a scammer bro. What  you not listening???',
  'yeahh 2 will be sufficient for 1 week ',
  'still havent done that?',
  " I've given zhestka a solid one for not filling me in with the plan",
  'same problem. i also have deposit 1hr from now. hope support fix this :)',
  'ill just say it now incase im not on later .. your welcome',
  'Sounds good! ,D',
  'house always wins ',
  'ppl begging they get muted, ppl crying for tips back, isn’t this begging? I think they should be muted, right?',
  'just lost my family to it now i need to sell to play more',
  'i have withdrawn 16700 inr yesterday its \nshowing withdrawal successful but still i  have not recieved to my account can anyone faced this issue money will come',
  'busted',
  'Exactly',
  'Thank you 🙏',
  'Cleaned out',
  'Lmfao this so damn entertaining',
  ' ',
  'build it uppp',
  'Coffee and pooing just go hand in hand ☕️☕️💩💩',
  'Please contact support regarding that matter',
  'Not even one fking win',
  'Helloooooo',
  'and a ciggy',
  'hello',
  'i drink coffee just to clean out the bowel lol',
  'Good luck',
  'Ayoooo',
  'Things are okay with T now ',
  'Hello',
  'Hope your winning today',
  'Oh nice drama i like it man ',
  'good luck session mannn',
  'it is right? Scamming people from their money and coming in this chat everyday and farm rain and beg people in dms when they hit, you are a junk',
  'Hello',
  'Bro that compounded interest joke had me dead 😂 we really living in the blackjack fun Bank now.',
  'im glad.',
  'u even got the evidence of how he is',
  'Man bad day lol',
  'Wish your having some luck legend',
  'thats exactly my daily routine. You a smart man. Good work',
  '+1',
  'Today we need to hit big!',
  'nothing new',
  'enjoy your session today !!!',
  'As for W, he was a mess last night. Really sad and heartbroken ',
  'Dear UnicornGod, bless me with the luck of a x3mil, not asking for much. thanks you',
  'yooo my g thank you maybe today  ',
  'ppl be desperate lol',
  "Hey, i didn't get the link to claim the last reel rumble challenge, others winners have it already. Can you take a look ? Thanks",
  'Need a leprechaun',
  'Bad bad day sir',
  'Rb been really slacking today, wow. Havent seen that fucker in over hour for sure',
  'good morning everyone   any luck this morning',
  'its coming stay sharp dont tilt fam 🍀🍀🍀',
  'Snis you are serious?',
  'you will  my broooo ',
  "god got ur msg it's coming bro 🔥🔥",
  'Hello folks',
  'Yall really think you can fuck with me? Haha wow. Save ur messages for ur begs. 🤡',
  'Need a fairygod eddie to smack me some hits',
  'how about a magic wand? 🪄',
  'sure i have the only thing is that he as been more time than me in chat so',
  'it wont lock up',
  'been a rough start to the day bro but hoping it turns around',
  'why would I lie lmao, Im telling people for month to not trust him but yeah people like being scammed',
  'Tha would be amazing to',
  'I will fight all yall fake fucks. What’s good?',
  'I believe 😊🤞🏼🍀',
  'will go to do some things, gl chat',
  '🪄🪄🪄🪄',
  'Going to California',
  'so about this 500x keno.. wen',
  'Dammit',
  '  ',
  'shut up bro you look like my homeless dealer',
  'time for bed',
  'DAMNNN',
  'Well there goes the poker tournament',
  'Lol',
  'yeah i understand bro he a old head and most OGs tend to believe his side of the story',
  'gl brooo!!!',
  '',
  '    break time mom ,',
  'Guys let me explain how homies/🥷/🧃 work here 1)if sumone tips u when they up 2)or u tip sum1 when u up:, 1)u should tip them when u up  2)when they up tip u',
  'he must be a baller.',
  'Whats wrong with polygon matic deposits ?',
  'Diamonds and Rust',
  'You will most likely need to check with support',
  'thanks for explain, i believe u',
  'Wish you win big today',
  'i lost a 200 again this morning but hit 200x on big bass 1000 60 cent bet cashed it out lol',
  'Same question about poly',
  '',
  'What happen bro.?',
  'hope max win I bless everybody',
  'ok',
  'inr deposit of 16700 is showing withdrawal successful but still not added to my account its been 25 hours can anyone faced this issue and money will be added',
  'Not sure jizy wanna try my addy',
  'they are delayed a bit. Need like hour or two to hit',
  'Patience people! LoL',
  'is trusted more than i am and one thing he did and i have screen he says luck how i destroy your credibility on blackjack fun chat',
  'Might test short sessions',
  'yeee slow and steady',
  'what heppen mannnnnnn!! Ok bro lfgg! Now is time to luck?',
  'Ohyea 😎🍻😎 💞',
  'sometimes they forget',
  'Wish you get your depo asap and wish its a lucky depo for you',
  'Low pressure session today',
  '',
  'You dont need to believe me, I can name like 20 people who is being scammed by  but people still believe him because he is in this chat everyday lmao',
  'I thought I would have birthday luck but clearly not. Just lost $20 on dice not the biggest lost Ik but it’s still mildly infuriating',
  'bro i will go the extra lenghts to get someone if they got me before evem if i dont win thats how it supposed to be',
  'If I ever win I would tip so many have dropped rains and I got 2 tips today I would definitely pay forward',
  'I think you missed my message ',
  'excuse me sir I am a scammer. Do you need scamming?',
  'Scammer get scam',
  'Whats  good guys ??',
  'Any bonus drop codes I just won 11k and lost it all😭',
  ' ',
  'Lol',
  'Damnn ☠️',
  'yeah i remember what u say for me  few days ago',
  'To be honest ,  hates scammer',
  'i did, sorry. i told you he must be in a mess, it cant be easy for him',
  'I know its hidden somewhere - those wins!',
  '',
  ',',
  'he knows he has that superpower but ur credibility can not be destroyed by one man Hes too small',
  'thanks for sharing 😅',
  ' ',
  "but wait fthere's more",
  'We can report his account for perma muted',
  'i dunno if sumone gets u when they up they cant expect a get back til u are up u cant be dont and they hassle u cause they didnt tip u when down',
  '',
  'so how does this scamming thing work, it seems profitable',
  " I can't believe it hurt him, men surprise you",
  'Why have not Ting  sound mom ,,',
  'Washed',
  'Good luck',
  'hey, why are you suprised? im not',
  'Disgusting asf',
  '',
  'Bruh  i was in idr coin swapped to usd to see ur wins ',
  'comeon for luck ',
  'Mods need to mute scammers for real, but the only thing they do is muting people post emotes and ask for a tip hahahaha',
  'oh no   what happened?',
  'Your very welcome lol',
  'Aparise is the one who hates scammer what you all talking about',
  'inr of 16700 is showing withdrawal successful but still not added to my account its been 25 hours can anyone faced this issue and money will be come or not',
  "I've never seen it.",
  'Lost 11k gonna depo another 5 talk think imma win it back?',
  'that is a correct logic too bro i wish everyone thought like you',
  'deposite bug ?',
  'pissed that carney won',
  'well, not exactly. we try our best.',
  'yes because there isnt a rule which stated that it isnt allowed to scam people, its a bit sad that blackjack fun is allowing this',
  "Because i have no self worth and i can't believe anyone would love me enough",
  'Cheers ',
  'Gl',
  'no.good. but thank u',
  'this is not support. go ask support.',
  '',
  'Rain rinsed',
  'hi',
  'Dang burst a x400 by miblackjack fun >.<',
  "I don't know how people think you're scamming them. just stupid if they are",
  '❤️🤏 good luck bro',
  'we have posted that  is taking loans and isnt paying back, which is considered scamming but yeah when we post the chat, we get muted',
  'I know man. People get upset when u have coins and they don’t. So they want u to tilt your session for a sen. Fuck that.',
  'True busting',
  '😅💪💪💪💪 bro',
  'Truth is i got nothing against u bro just let peace reign if u feel i owe u so much tell me how much and i will take a loanfrom the bank nd pay u',
  'good luck tho',
  '',
  'Hope your guys gaming is good wins for you all I just had no luck today not my day',
  'anything good today?',
  '',
  "To all of you who said I couldn't do it..you were correct 🤣🤑🤑🍀🟢💚",
  'dont tell me that you believe that fuckface',
  "Don't mind them  they won't give you profit anyway",
  'What’s a coin',
  'lol',
  'ImFakked Frog',
  'get the win',
  "i can't see that pic show expired",
  "you lend me 5k I'll get you back promise",
  'they think by getting on their alt accounts and bullying me it will change anything. Haha wow these peeps are desperate asf',
  'someone robbed the whole ATM (crypto) machine from the gas pump now i gotta drive to center tondepo 🫣 no hope for me lol no sleep cant leave too suny',
  'Lmaoo',
  'heloooooo',
  "If you can't do it, I can do it",
  'hellow all  am  back ',
  '',
  'master of puppetss',
  'D i s g u s t i n g',
  'check tg',
  'Wish you win big',
  'redness dice again',
  'Instead of getting on my nerves and calling me out every chance u get   be a man bro being bitchy is a thingfor bitches',
  'Lolo L',
  'Suck my dick blackjack fun piece of shit site fu retarded shit',
  'alot haplened my friend 😂😂😂 how u doing ?',
  'Down 5k might be it bois',
  'i would do that in a heartbeat for you. ❤️ but I don’t sen remember? Only scam',
  'new layout',
  'hopping so',
  'that has to be the lamest bet share i’ve ever seen',
  'well cum back then. How long have you been away?',
  "I don't pay attention. did you give him money and he ghosted you",
  '',
  'same man',
  'wwww',
  'Cant farm ,uwu ',
  'wish you win big legend 🙂',
  'leave it bro, nobody cares and he isnt gonna pay back /  he ghosted like everyone who gave him money, he only pays 1/2 people back',
  'That,s the point  stop hating',
  'good luck blackjack funrs',
  'i posted just one screenshot that prove that he scammed me and atfer that he tryed to destroy my reputation on chat',
  'haha',
  'Poker still alive',
  'has already gotten me back before, lmao and many others and i have proof of that as well. so sometimes it happens boys when ur down bad chill.',
  'Best of luck',
  '2 days   hahahaahaha',
  'What can you say about a motherfucker who begged in other casinos chat hahaha',
  'dead dead keno',
  'krazy klown kooked',
  "ughhhh man    Sounds super frustrating.... I'm fine thank you ... just came,  starting slowly slowly super slowly",
  'laeememe leememmememe',
  ' ',
  "y'all be getting loans like dat? damn",
  'you must have taken a good rest after you ripped  your weekly',
  "I put all my trash in my neighbors garden, he was not happy, but when I told him , one man's trash is another's treasure.. he asked for more🟢🍀🤣😅😂",
  'was making food. how are a',
  'exactly',
  'No one cares anyway 😥',
  'hey bro 🤗🤗',
  'Damn 3 sceter again',
  'im sorry. i havent seen him do that, and you know we cant control what you do outside this chat.',
  'yeah u right Apa does get u back when he can but he needs to use same patience i use when i dont hear from him instead he out calling me a beggar',
  'almost but missed',
  'haters gonna hate',
  'well.. ok then',
  'The green manalishi with two pronged crown🤟🤟🤟',
  'theres no sense in nonsense',
  'Congratulations catchers',
  'u know when u are good to get people ignore any other pressure the ones that are bad are people that take but dun sen wen up i can confirm you sen',
  'Im wired i cant even sleep lmafo what kknd of problems i be having 😂😂😂😂😂  and yeah have an easy day i hope enjoy',
  'bro they really reaching. Haha I don’t know what they are trying to prove here. I don’t care about others opinions. I do my own thing so 🤷‍♂️',
  'cmon hilo ripped',
  'deposit not going through',
  '   ',
  'never ',
  'hi therer',
  'oof',
  'you are fine as long as you follow the chat rules.',
  'Clown being a clown forever 🤡',
  'you guys are like woman just bla bla bla',
  'Oh god everything fuck',
  'good evening',
  'love is blind blackjack fun, you are hitting on others and thats fine, but you need to hit back at your ture love too!',
  "I don't know what to say if its a tip, don't expect it back. would be nice but it narrows my list down quite a bit",
  'becouse im not the only one that he fucked and if he doesent send me back my money im going to do a topic blackjack funforum',
  '',
  'anyone seen lilpurge recently?',
  'Need some luck today. I can use a good cash out',
  'just sen all',
  'Hey  💐💐💐',
  'my love u know am all about good vibes am gonna let it rest hows ur day going hope greeat',
  'wish I could help you somehow   good night sleep is important man',
  'aoo laeem winning🤔',
  "ok, i understand, but i dunno what we here can help with if that's something you do outside this community.",
  'did i breake any rule posting that link? if i did im sorry didnt know',
  'ehmmm wtf?  super bonus gekauft',
  'how are u bro..i hope you recovered your previous losses g',
  'best of luck ',
  'it’s crazy how hard they trying to ruin my name even tho I don’t give a fuck and try ruining my own name all the time. wtf is happening',
  'yoo',
  'omgggg',
  'My withdraw complete plzss help',
  'Nice win',
  'Good luck all',
  'almost max win? 😍😍😍',
  "hello 👋 how are you today? i haven't forget about the cake 🎂",
  'nice',
  'you back legend congrats 🎉👏',
  'zzz',
  "Apa is one of the realest here.. that's proven.. I've been down bad with few months LStreak but he still helps when he can..",
  'wen ya get some let me know im done for now@  was ^^  not by far',
  "we can't help you",
  'oooooof',
  'See how this turned on u really fast 💨   avoid me next time',
  'uufufufuf greeenen itsss grrnnene',
  'oh yumm thank you ☺️',
  'waka waka e e',
  'Unemployment starts today! Pray for a big win for me folks!n! 😂',
  'best of luck who still have balance 😑',
  'HOLY shit bonus pays broooooooooooo, robinhood ❤️❤️❤️❤️',
  'am gonna leave my bucket here for a while',
  'Ty',
  'Ty for trx',
  'cool',
  'Hello',
  'what happen man?',
  'in our country Ivana Alawi is so hot and pretty :)',
  ' ',
  'Goof luck',
  'finito 🤣',
  'hmmm all the,best',
  'oh, you are very welcome! hope you have a great time today!',
  'hello there',
  'just dont be stressed about  that and forget, you know how much i gived and nobody tip me anything but  hahah  but i dont care',
  'good luck too age17',
  'Thnx man.. i value ur wish! And k wish it was night time its 3 37 pm if the sun wasnt beaming and no rush hour i woulda been gambling right now lol',
  'did the seed hot 250 or 500x yet',
  'good luck bro',
  'hahahaha omg bro your too much. Words mean shit You clown. Actions matter and your actions show you a BITCH',
  'hi',
  'ya I shall. I lost too no luck hagd',
  'Withdraw no complete',
  'good luck too',
  'Did everyone without me get the bonus mail today?',
  ' ',
  'its not what u can do its what all other players can see and be aware ov him. in Italy we say if u steal once u will do it again',
  'imreally sorry, i dont know who that is 🤔 but, I will trust you!',
  'somebody pls give free money',
  'Ok i go  enjoy ',
  'hi there buddy \\',
  'got no bonus mail',
  'Beg beg beg beg',
  'on your way. Check notif',
  'i am sorry you have to deal with this. I don’t know why they so triggered',
  'Am I allowed to post proof of people scamming in blackjack funcommunity.com @ mods',
  'Ez',
  'why dear?',
  'Good luck everyone',
  "I didn't   I never do actually? ///what do you mean  ?",
  'Bonus mail!? :o',
  'just enyoj the beautiful day ☺️',
  'gm guys  glgl',
  "you have a point here. and I wish this doesn't happen to you again. h good luck 🍀🍀🍀",
  'Busted',
  'Haha facts bro, who cares what they think when you living rent free in their heads 😂',
  'good luck as well mate',
  'Huh ',
  'i love to get blackjack fun mails XD',
  'Blame Eddie',
  'Withdraw no complete 3hur ho geya',
  'keep try broo',
  'yall clowns. 3 vs 1 and I am still standing. Suck my dick',
  'Thanks hun  🥰',
  '',
  'u such a bot LOL',
  'im not bothered at all. i wish you guys could clear things up .',
  'Hello Have a nice shift 💕 💖 💗',
  'what do you mean   someone was pulling scam in our chat earlier?',
  'Hello year',
  'always red dam',
  'sk',
  'play safe bro nd enjoy your food u can trust your bro next time glgl got u wen i am up for real gl',
  'Shit man',
  "always red. that's our destiny",
  'same dear always',
  'be a good boy',
  'green is all that matters, green dots, green bets, green confirmations on the block chain and the greens that come out the atm',
  'Go play some games take your angry out on slots lol',
  'best of luck',
  'hello, sofi, dear! how are you today? 🍀🍀🍀',
  "It's been an hour and my two deposits haven't arrived yet",
  'Hello there Sofia, I hope you have a good and lucky day today!  🍀',
  'hmmmm',
  'redd',
  'rb we miss u',
  'i do t start fights online. Can’t find u in person so what’s the point of getting worked up? It’s pointless.',
  'bro I dont care about what you say, I just dont want you to scam other people. /  nope someone IN this chat is',
  'Good luck guys 🍀🍀🍀Lord knows i try to be genuine',
  'likewise dear',
  'i spent all my pocket money on blackjack fun',
  'it clear dont worry he will be exposed to the community after i talk to Sanjat and ask her if i can post our conversation',
  'Thank you 💕',
  'Hy',
  'thank you   💚Best of  luck 🍀',
  "let's break the spell with some greens! 🍀🍀🍀",
  'ye',
  'Hi',
  'Ting please  ',
  'i know bro u deserve respect',
  'Gl gl everyone',
  '   ',
  'how are u guys',
  'how is luck today bro?',
  '',
  'Withdraw no complete',
  'my poloygon usdt depo stuck, any one have same issue>',
  'Sorry for the drama chat. But some people just don’t hustle. So every dollar feels like their last. 🤷‍♂️',
  'waiting luck dear 😁  Thank you 💕',
  'Well, as they say: I like turtles',
  'ahhh somebody remebers me',
  'hello, dear friend!',
  'I will when I have a balance',
  'same too you mate',
  '',
  'no bro  is a pretty lady not bro',
  "A wise man once said.. don't gamble..after he lost all of his money ❤️‍🔥💩🍀💚🟢🤑",
  'nice',
  'nah this day is hell again',
  'Withdraw complete but no add many my wallet',
  'kk',
  'You can send username and we will have a look   Can happen we missed something, no doubt about that ...',
  'so, we need bucket first?',
  'yes a balkan girl',
  'Glu glu I am going to eat my phone',
  'manifesting a good game today',
  '',
  'Good luck today everyone if you are betting',
  '',
  "how wise  Yes, I'll take my bucket out now \\____/",
  '',
  'take some snacks , dear. not the phone',
  'good luck on that buddy',
  'please do and make sure to let everyone know my level of Skem is expert',
  'A beautiful Balkan girl   dont forget that 😊',
  '',
  'hi chat',
  'Playing light and focused',
  'wen top monthly',
  'hy dear/?',
  'HEY',
  'Tap felt natural',
  'hi',
  'Aw   You are the one...? Somehow I doubt that',
  'heyy buddy',
  'omg srry you are Queen 👑.. yeah u given too much i seen many times dear  yeah got it bro Balkan Girl',
  'guys, money is the root of all evil. so send me your balance',
  'Ugh',
  'nice calm day',
  'thats at least creative',
  'careful what u say man they turn in you quick 😂',
  "VIP host just said top-up months they will be within this week didn't say a day",
  'GG good luck guys',
  'I love to give and have nothing in return',
  '🏈🏈',
  'what busting said',
  'u deserve more than that wish i could send u my bank right now',
  'Shiiiiiit',
  '😂',
  "he also said ..don't eat yellow snow..after he lost all..well you know the rest🤣🍀🟢💚",
  'see that s the point heis here more than me and people trust him',
  'ughhh',
  "They say when you have a host, you get to receive extra bonuses. I didn't know they meant to say rainbot, instead of host.",
  'and monthly will be this month',
  'true',
  'what are top up months?',
  'still missing fbot',
  "let's go",
  'But biiiir',
  'it is happening outside the chat, and I see every day more people getting scammed by him.',
  'Just kidding xoxo, I am tired gonna eat something',
  'cmon',
  'good  morning chat',
  'I will take charge of this and go all in on 1 plino ball. evil begone',
  ' rinse mode not endinnnn',
  "yeah i also did it wen i won queen but they keep ignoring so let it be .. I don't expect..now also down but I'll comback stronger 💪",
  'indeed, there is so much to learn from that man',
  'I meant the vip top up bonus',
  'why are you so obsessed with me? You need to get off my dick dude. Like seriously LoL',
  'cashout broooo?',
  'Wish you win big today',
  'No luck',
  'good luck 🍀 Evil be gone',
  'go have some nice food!',
  'brah',
  'If I win max you first on the list',
  'bssss',
  'u need to give me back my 150$ loan i given to u and thenu can get the fuk out',
  'how is bestie? 😩',
  'Hlo',
  "can't figure out what's going on... Just came... some beef between couple of players going on definitely 😒",
  'lol good luck getting any money out of him',
  'Busted out of tournament',
  'notbad',
  'you think he will pay back 😆😆😆😆😆',
  'Anyone have any fat wins yet?',
  'Just so ugly he was tryna drag me now getting dragged with receipts',
  'oh snap you too? Wow so how are you related to them? They your alts?',
  'we are all obsessed with you, i have a bubble gum statue of you in my closet, just need some of your hair to complete it',
  'Only fat losses. no fat wins',
  'try keno bro 3 number, 1 18 20 haha',
  'ill expose u on community after i talk to sanjat and as u tolm me u will see how your credibily is destroyed',
  'miss ofc',
  'nic',
  'gz',
  'Deposit Pending keno 😁',
  'dead',
  'Niceee',
  'Love you to the core blackjack fun!',
  'how many episodes does this soap opera have, is it worth making coffee or am i gonna miss more',
  'Grats to the winners',
  "Wow you guys actually loan that much to people you don't know you guys are truly amazing people you deserve good luck your way",
  '<===== Mods ban this SCAMMER',
  'LFG  🍀🍀🍀get it the big ones i mean Max',
  'Successfull all in?',
  'almost same catchers again wtf 😒',
  'Best of luck to everyone,)',
  'thanks dear i will do same for u wen i am up or on plat bonus which is close .. praying for your max win Queen 👑 play safe',
  'What is it today? Sugar Rush or Wanted?',
  'hope you guys get some recoup and win big 😎',
  'thanks',
  'make coffee, lay down and enjoy',
  'every day, morning, night, or noon',
  'make a coffe Evo',
  'Thank you',
  'Ruuun ittt uuuppp',
  'Bro I’m a scammer. So what. Fuck off already',
  'nah man, im ripppped',
  'where do u find loan sharks',
  'okay guys thanks',
  'Bring some popcorn 🍿',
  'Gates just rinsed me',
  'misspelled my name lol',
  'this chat getting so interesting',
  'celebate good times yall cmonn',
  'lol to many retards here',
  'ops',
  'trying both, unsuccessfully so far',
  '',
  'missed call 🤙 what u hit bro?',
  'busted',
  'you want it buttered? we got salt in here already 😂',
  'everything rinses her',
  'Is there a deposit delay for everyone ?',
  'hey',
  'Nps bro! 😊',
  'I blame Eddie for always making sure i lose if i wasn’t losing so much yall would know how generous my heartt truelly is',
  'that squirrelly slot, 7k x',
  'Yeah 🤣',
  'always brother',
  'no money 4 depositing 🤣',
  'im shocked by you tho. U seen my generosity first hand in my group. U must be the main and Nino ur alt? Makes sense now. I heard u had 30 accts',
  '🫡🫡',
  'who are the retarded?',
  '❤️🤏',
  'oh my goodness congrats brother 😉',
  'Good luck',
  '7 k x you win show me this sexy win',
  'man shut the act',
  'Woah u still hittin',
  'nice keep em coming',
  'congrats >3',
  'Push it to the limit  get it',
  'You can do',
  'Does anyone has a delay on his deposit ?',
  'So mad',
  'I’m Rb what did I do to derserve this cold shoulder and I’ll just say mean and hurtful treatment. We’re partners teamwork',
  'ur weird af, what group? the one where I kept sending you tips and you just kept ignoring? Man i judge by action and not your yapping',
  'Okey if i manage to hit another $10 with these unicorncoins i will share a fiver again for good luck :D',
  'nice rain',
  'cmon fbot',
  'are you?',
  'nothing today',
  'Don’t dude. Just let them think what they want.',
  'nope',
  'lol u going mad alt double account ahahha',
  'ofc miss',
  'it was 530 this morning',
  'It stopped for awhile ,  thanks',
  'yeh nice catch 😁 how is it going today?',
  'why would I need alts? :D',
  'in dms  knows every thing about it, but his issue is that he doesnt pay back',
  'ok ✅',
  'congratsb',
  'thanks',
  'that is a nice 500x!',
  'how we doin?',
  '🥷🤔?',
  'ipjpoj',
  'Good morning everyone, even the lowlifes and beggars!!!',
  '',
  '',
  'bro I literally just said that to your alt flystar. Said the same thing. Talks cheap actions matter. How ironic. Hmm',
  'Slots filed me today so hard without Vaseline',
  'KennyB76\nYour VIP Progress\n92.77%\nPlatinum II\nPlatinum III Not going to happen for at least 2 more months🙄🫣💩',
  'I am up 80k this month with 3mill wager, im good. I dont need to brigade 2$ tips in here',
  'ty broski',
  'Good morning',
  'you also getting scammed by him lmao? Thats already 4 people whobare active right now hahahah and people still believe him',
  'Good morning      Enjoy your day',
  'how much did u build ur gal',
  'good 😁',
  'cant hit shit',
  'What a drama, i like it guys ',
  'Where my holy water heroes at?',
  'flystar is my alt :D did you do too much drugs again?',
  'up 80k? That looks sweet',
  'i have only one account bro u fighting with weapons that dont exist',
  'How many bonus for platinam 1.',
  'well you got me 2 for 2 there. goodmorning',
  'rish bish xD',
  'nice hit',
  '       ',
  'gl all',
  'HI',
  'Youre a psychic. Haha Nice to see you',
  'rainbot racist or my name is cursed 😩',
  'come back comeon',
  'Hmm I haven’t read one of their messages. LoL',
  'really? ',
  'why have u never sent me a tip since am one of ur alts 😂😂😂',
  'and alskin is not here btw',
  'whos my lil good rainbot?',
  '',
  'same shit',
  'why there is no weekly??',
  'Hahahaha',
  '',
  ' ',
  'they are soo many people Who are scammed by 1 man lmao',
  'misspelled my name',
  'there was a weekly',
  'damn 😭 soon bro I hope so',
  ' tastes good',
  'ive sent out hella hella but to actual real people, not ones that cry in blackjack fun chat for missed 1$ rains :)',
  'try one buy on sugar rush 1k',
  'Drugs are really bad fr',
  'hello, there! enjoy your coffee',
  'Breakfast time',
  'heyhooo :) have a great shift ',
  'fvck this pragmatic',
  'I’ve tried every single coin six deposits, and every one of them ripped not even capable of going above the initial balance this is beyond ridiculous',
  'no luck',
  '',
  'Cause I cry after every rain I miss. You are so fucked. Hahaha',
  '',
  'yum yum in your tum 😉',
  'Yeah skem',
  'I missed email bonuses aside from monthly',
  'Platinam 1 how many bonus???',
  'mmmmm anything nice?',
  'dont mind him bro just let it go',
  'hagn',
  'and people still trust him they dont know they will be blocked and ignored he just need to get enough from them',
  'fuck my day too much hard to win',
  'let me ask you something',
  'Damn i missed a dollar rain apparently',
  'r bbbbb',
  'Comgrats',
  'try uni or trump I heard it hits good',
  'only down',
  'yeah bro - wallah krise',
  'am all ears 👂',
  '10 fvcking d*ad spins',
  'The guy whos buddies with greeky and thinks he is that important posting his 20$ wins and yaps about his CIRCLE when he needs money. Im good man im fuckin good',
  'no chance to win',
  'thank you! looks like a nice one! have a great day!',
  'bruh, got all max upgrades on big bass and payout 25x ',
  'always bro 😂',
  '     ',
  "hope you still remember, who's beg you for gas fee in dms and he still act like a clown every day 🤡",
  '',
  'Lfg',
  'i could use a bier',
  'try le Bandit bro old is gold',
  'lol 20$ wins u right lol',
  'When montmhy',
  'LoL',
  'hagn !💕    ah French toast for the gf and bacon and eggs for me and fruit cup for babys 👶',
  'isnt that the average blackjack fun player? : D',
  'Any friend out there',
  'already ahead of you 🍻',
  'next month   ',
  '😂😂😂bro plz lets leave it alone',
  "now I'm tired and sleepy",
  'mmmm all sound delicious and healthy! have a great meal!',
  'got none left I’m cooked to a fkn crisp',
  'any luck brother?',
  'prooost',
  'I dont even know who are in his circle, lmao.',
  "i wont forget it man🤣🤣🤣 they're gangster of shit.",
  'fuck u edd',
  'Any1 help us out haha',
  'oh, no. no need  for that',
  'i feel u',
  'My wager went from 550k to 470k in 3 days I hope top player monthly comes out of the 30th and not the 1st',
  'can’t catch a break on originals',
  ' maybe tg soon I hope!',
  'every one who can slide a penny to him',
  "80k up with 3m wager? Now that's how you stay quiet and let your numbers do the flexing 😎",
  'juicy wager',
  'i started that circle shit when i joined but they highjack the idea 💡 to rip others off cos i was low rank',
  'doesnt matter top isnt based on 30 day wager but for the month of april.',
  'ty ty hagd',
  'I will be making shortly an omellette with Italian spicy sausage and smoked cheddar. Not hungry yet!!!!',
  "top need minimum 250k wager for eligible bro don't worry they will drop for u also praying for u gl",
  'i posted all my hits and cashouts on twitter always :)',
  'Hi',
  'sup',
  'End of month',
  'Originals today, are like the  of the century',
  'keno is a fucking skem bro',
  'U dont need to Prove shit bro u been solid from the Jump  i follow u on x',
  'Broooo fuck me i wish i had balance ',
  'still on goated?',
  'your brother always check ur x post legend glgl',
  'sounds super delish',
  'hbu brotha ???',
  '',
  'It’s beyond Retarded',
  '3rd hit on auto for mines',
  'gimme my wet toertilla',
  'Those all solid dudes. Good peeps to have on your side. 🫣😆',
  'mein-bot',
  'damn',
  'damn missed poker also... ffs',
  'Good luck 🍀 everybody',
  'beyond imagination',
  ' ',
  'Wtf',
  "And you're right, my friend, there's no point in attracting negative energy.",
  'Penis',
  'wen win',
  'PENIS',

  'Good luck everyone!',
  'Let’s go! 🔥',
  'Big win incoming',
  'RIP my balance 😅',
  'Double or nothing',
  'Who else on a heater?',
  'Just hit 50x 😎',
  'Feeling lucky today',
  'Come on green',
  'GGs everyone',
  'LOL that 1x hurt',
  'Max bet vibes',
  'Let’s break the bank 💸',
  'I need a miracle spin',
  'This game is too fun',
  'Back-to-back wins incoming',
  'Clutch roll',
  'Anyone else sweating right now?',
  'Hahaha that was close 😂',
  'Cashout or cry',
  'Small bet, big dream',
  '10x train coming 🚆',
  'That drop was nasty',
  'Let’s go team green',
  'One more spin',
  'Easy money',
  'Okay okay, I’m feeling it now',
  'Crazy luck tonight',
  'Is this even legal?',
  'Bet smarter not harder',
  'My wallet crying right now',
  'Luck check',
  'Who else on auto bet mode?',
  'That bounce was wild',
  'Manifesting a win',
  'Plinko gods be kind 🙏',
  'Can’t stop now',
  'That 0.01x pain',
  'We all in this together',
  'Big win coming',
  'Hit 100x 😲',
  'Slow and steady',
  'Cashout gang',
  'I blinked and lost',
  'Feeling blessed',
  'Risk it for the biscuit',
  'My streak is unreal 🔥',
  'Nice hit',
  'Double hit incoming',
  'Plinko tower time 🪙',
  'RNG hates me',
  'I’m calling 20x next',
  'Let’s break the site',
  'Stacking wins today',
  'Where’s my lucky charm?',
  'This seed is cursed 😭',
  'Never give up',
  'Reroll for luck',
  'Imagine 1000x right now',
  'Lucky vibes only ✨',
  'Risk level: MAX',
  'Win or lose, we vibe',
  'Too close, man',
  'Broke but happy',
  'Legendary moment 💥',
  'I swear this site knows',
  'All in again?',
  'I need coffee and luck ☕',
  'Nice one',
  'Luck activated ✅',
  'Win streak mode',
  'I’m chasing my losses',
  'RIP bankroll 🪦',
  'Back from the dead',
  'Never been this hyped 🔥',
  'Insane luck right now',
  'That bounce was illegal',
  'One more for the dream',
  'Comeback season',
  'Stop. Spin. Win.',
  'Easy claps 👏',
  'House shaking right now',
  'Let’s go purple gang',
  'Pray for my next bet',
  'Plinko gods watching 👀',
  'Luck is my strategy',
  'Risk management? Never 😏',
  'We roll, we win, we repeat',
  'That’s my biggest win ever',
  'Suuuper close',
  'Hit 200x!! 🔥',
  'Hands shaking',
  'Who needs sleep?',
  'All in or all out',
  'Yooo that was crazy',
  'LOL what was that bounce',
  'Calculated luck',
  'The chat is lucky today',
  'Sending positive RNG ✨',
  'Time for revenge',
  'Might cry if I lose again 😂',
  'You cracked',
  '1 tap = 10x',
  'Who believes in luck?',
  'Need a win asap',
  'I’m addicted to winning',
  'Let’s go team red',
  'Insane streak right now',
  'Hold my beer 🍺',
  'Luck meter 100%',
  'Another day, another W',
  'Don’t blink',
  'I’m shaking',
  'That was smooth',
  'Win train continues',
  'Send me your luck',
  'That was unreal 😲',
  'Why am I like this 😂',
  'Feeling rich 💸',
  'Call me lucky charm',
  'This site loves me today',
  'From broke to beast',
  'I’m in disbelief',
  'Ain’t no way that hit',
  'That payout tho',
  'What a comeback!',
  'Good vibes only ✌️',
  'Respect the RNG',
  'I swear it’s rigged',
  'Raining wins',
  'One loss, ten wins',
  'Smell of profit',
  'Nice streak',
  'Losing gracefully',
  'Bounce of destiny',
  'That was too close',
  'Winning never gets old',
  'RNG on my side today',
  'Can’t stop smiling 😄',
  'Teach me your seed',
  'It’s my lucky day',
  'Luck over skill',
  'Oh noooo',
  'Plinko bounce of hope',
  'Insane multiplier',
  'Should’ve cashed out',
  'GG RNG, you win',
  'Bet. Win. Repeat.',
  'Holy smokes',
  'Profit city',
  'Who’s still up?',
  'Riding the wave',
  'Blessed bounce',
  'Send some luck my way',
  'That payout looked tasty',
  'Unreal moment',
  'LOL I’m cursed',
  'I called it',
  'Why is this so fun',
  'Let’s go fam',
  'Stacking green',
  'Cashout at 10x or bust',
  'Vibes only 🔥',
  'No way that missed',
  'House edge crying',
  'We cooking today',
  'Let’s hit 69x',
  'Winners only club',
  'Who’s next to win big?',
  'Auto bet magic',
  'Plinko rain incoming',
  'That pattern tho',
  'What a rollercoaster',
  'Good luck everyone',
  'Team chat OP',
  'Let’s make history',
  'Okay that was clean',
  'I need a break',
  'Still chasing 100x',
  'RNG moment',
  'Big brain plays 🧠',
  'That drop',
  'Next hit gonna be massive',
  'Win or learn',
  'Balance check',
  'My heart racing',
  'Not leaving till 10x',
  'Certified win',
  'The dream lives on',
  'Imagine 999x',
  'Who else addicted?',
  'GG everyone',
  'Time for one more spin',
  'The vibes are immaculate',
  'Can’t stop won’t stop',
  'We up boys',
  'Let’s gooo fam',
  'Raining wins again',
  'Almost cried that round',
  'Luck is real',
  'Plinko’s got jokes today',
  'Hitting 10x like it’s nothing',
  'Rolled a 1x',
  'Team W assemble',
  'Insane game today',
  'Still laughing',
  'RNG please behave',
  'Never bet against vibes',
  'Woohoo jackpot vibes',
  'Epic round guys',
  'Laughing through the losses',
  'Luck train continues',
  'Chat going crazy',
  'I can’t believe that hit',
  'It’s showtime',
  'Rollhub is wild today',
  'So close but yet so far',
  'Win streak maxed out',
  'Okay RNG, we cool again',
  'Back-to-back W',
  'That was insane',
  'Still can’t believe it',
  'Alright one last bet',
  'Who’s winning big today?',
  'Lucky numbers only',
  'I’m screaming',
  'Crazy bounce of fate',
  'Another clean win',
  'That was satisfying',
  'My balance loves this game',
  'Just vibing and betting',
  'We legends today',
  'Lucky squad rise up',
  'Bruh moment',
  'Chat full of winners',
  'My luck is unreal',
];

export const botUsers = [
  { id: '68fa1d1c38343344a3bbe542', username: 'HighStaker' },
  { id: '6900c723d64415d8f3c657c0', username: 'Hamzam' },
  { id: '6902649a97d84b0b1cefc3d0', username: 'MeGingerPale' },
  { id: '69027ba697d84b0b1cefcbfa', username: 'Kuldibpa' },
];
